import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Button, FlatList, Image, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { Session } from '@supabase/supabase-js';
import { mobileApi, type Customer, type CustomerDetail, type MaintenanceJob, type Quote, type QuoteDraft, type Store, type Today, type Vehicle, type VehicleDetail } from './src/mobileApi';
import { mobileConfigurationError, supabase } from './src/supabase';

type Page = 'stores' | 'today' | 'vehicles' | 'vehicleDetail' | 'maintenance' | 'maintenanceDetail' | 'customers' | 'customerDetail' | 'quotes' | 'quoteCreate' | 'quotePreview';
const operationKey = () => `native-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
const yen = (value: number | null | undefined) => typeof value === 'number' ? `${value.toLocaleString('ja-JP')}円` : '-';
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString('ja-JP', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '-';
const escapeHtml = (value: string | null | undefined) => (value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);

export default function App() {
  const { width } = useWindowDimensions(); const tablet = width >= 720;
  const [session, setSession] = useState<Session | null>(null); const [stores, setStores] = useState<Store[]>([]); const [store, setStore] = useState<Store | null>(null);
  const [page, setPage] = useState<Page>('stores'); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [vehicle, setVehicle] = useState<VehicleDetail | null>(null);
  const [today, setToday] = useState<Today | null>(null); const [jobs, setJobs] = useState<MaintenanceJob[]>([]); const [job, setJob] = useState<MaintenanceJob | null>(null);
  const [customers, setCustomers] = useState<Customer[]>([]); const [customer, setCustomer] = useState<CustomerDetail | null>(null); const [quotes, setQuotes] = useState<Quote[]>([]); const [quote, setQuote] = useState<Quote | null>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const [quoteTitle, setQuoteTitle] = useState(''); const [itemName, setItemName] = useState(''); const [itemPrice, setItemPrice] = useState(''); const [idempotencyKey, setIdempotencyKey] = useState(operationKey());

  useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { if (session) void loadStores(); }, [session]);
  async function run<T>(task: () => Promise<T>) { setLoading(true); setError(null); try { return await task(); } catch (reason) { setError(reason instanceof Error ? reason.message : '処理に失敗しました。'); return undefined; } finally { setLoading(false); } }
  async function loadStores() { const next = await run(() => mobileApi.stores()); if (next) { setStores(next); if (next.length === 1) await selectStore(next[0]); } }
  async function selectStore(next: Store) { setStore(next); await openToday(next); }
  async function openToday(target = store) { if (!target) return; const next = await run(() => mobileApi.today(target.id)); if (next) { setToday(next); setPage('today'); } }
  async function openVehicles(query = search) { if (!store) return; const next = await run(() => mobileApi.vehicles(store.id, query)); if (next) { setVehicles(next); setPage('vehicles'); } }
  async function openVehicle(next: Vehicle) { if (!store) return; const loaded = await run(() => mobileApi.detail(store.id, next.id)); if (loaded) { setVehicle(loaded); setPage('vehicleDetail'); } }
  async function changeVehicleStatus(status: string) { if (!store || !vehicle) return; const next = await run(() => mobileApi.updateStatus(store.id, vehicle.vehicle.id, status)); if (next) setVehicle({ ...vehicle, vehicle: next }); }
  async function addPhoto(camera: boolean) { if (!store || !vehicle) return; const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError(camera ? 'カメラ権限が許可されていません。' : '写真ライブラリ権限が許可されていません。'); return; } const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.8 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.8 }); if (result.canceled) return; const uploaded = await run(() => mobileApi.uploadVehicleImage(store.id, vehicle.vehicle.id, result.assets[0])); if (uploaded) await openVehicle(vehicle.vehicle); }
  async function openMaintenance() { if (!store) return; const next = await run(() => mobileApi.maintenance(store.id)); if (next) { setJobs(next); setPage('maintenance'); } }
  async function openJob(next: MaintenanceJob) { if (!store) return; const loaded = await run(() => mobileApi.maintenanceDetail(store.id, next.id)); if (loaded) { setJob(loaded); setPage('maintenanceDetail'); } }
  async function updateJob(status: string) { if (!store || !job) return; const next = await run(() => mobileApi.updateMaintenance(store.id, job.id, status)); if (next) setJob(next); }
  async function openCustomers(query = search) { if (!store) return; const next = await run(() => mobileApi.customers(store.id, query)); if (next) { setCustomers(next); setPage('customers'); } }
  async function openCustomer(next: Customer) { if (!store) return; const loaded = await run(() => mobileApi.customerDetail(store.id, next.id)); if (loaded) { setCustomer(loaded); setPage('customerDetail'); } }
  async function openQuotes() { if (!store) return; const next = await run(() => mobileApi.quotes(store.id)); if (next) { setQuotes(next); setPage('quotes'); } }
  function startQuote() { setQuoteTitle(''); setItemName(''); setItemPrice(''); setIdempotencyKey(operationKey()); setPage('quoteCreate'); }
  async function saveQuote() { if (!store || !customer) { setError('見積を作成する顧客を選択してください。'); return; } const unitPrice = Number(itemPrice); if (!itemName.trim() || !Number.isSafeInteger(unitPrice) || unitPrice <= 0) { setError('明細名と正しい販売価格を入力してください。'); return; } const draft: QuoteDraft = { title: quoteTitle.trim() || undefined, customerId: customer.customer.id, vehicleId: customer.vehicles[0]?.id, issueDate: new Date().toISOString().slice(0, 10), items: [{ itemType: 'service', name: itemName.trim(), quantity: 1, unitPrice, taxRate: 0.1 }] }; const saved = await run(() => mobileApi.createQuote(store.id, idempotencyKey, draft)); if (saved) { setQuote(saved); setPage('quotePreview'); } }
  async function openQuote(next: Quote) { if (!store) return; const loaded = await run(() => mobileApi.quoteDetail(store.id, next.id)); if (loaded) { setQuote(loaded); setPage('quotePreview'); } }
  const quoteHtml = useMemo(() => quote ? `<html><body style="font-family:-apple-system,Arial;padding:28px;color:#102A43"><h1>御見積書</h1><p>見積番号: ${escapeHtml(quote.quoteNo)}</p><p>宛先: ${escapeHtml(quote.customerName)} ${escapeHtml(quote.customerHonorific || '様')}</p><p>車両: ${escapeHtml(quote.vehicleLabel)}</p><hr/>${quote.items.map((item) => `<p>${escapeHtml(item.name)}　${item.quantity} × ${yen(item.unitPrice)}　= ${yen(item.amount)}</p>`).join('')}<hr/><h2>合計: ${yen(quote.totalAmount)}</h2><p>発行日: ${escapeHtml(quote.issueDate)}</p></body></html>` : '', [quote]);
  async function exportPdf(share: boolean) { if (!quote) return; const result = await run(() => Print.printToFileAsync({ html: quoteHtml })); if (result && share) { const available = await Sharing.isAvailableAsync(); if (!available) { setError('この端末では共有機能を利用できません。'); return; } await Sharing.shareAsync(result.uri, { mimeType: 'application/pdf', dialogTitle: '見積書を共有' }); } }
  async function printQuote() { if (quote) await run(() => Print.printAsync({ html: quoteHtml })); }
  const nav = <Nav active={page} onToday={() => void openToday()} onVehicles={() => void openVehicles()} onMaintenance={() => void openMaintenance()} onCustomers={() => void openCustomers()} onQuotes={() => void openQuotes()} />;

  if (mobileConfigurationError) return <Centered message={mobileConfigurationError} />;
  if (!session) return <SafeAreaView style={styles.screen}><Text style={styles.brand}>GARAGE LINK</Text><Text style={styles.heading}>スタッフログイン</Text><TextInput style={styles.input} placeholder="メールアドレス" autoCapitalize="none" value={email} onChangeText={setEmail} /><TextInput style={styles.input} placeholder="パスワード" secureTextEntry value={password} onChangeText={setPassword} /><Button title="ログイン" onPress={() => void run(async () => { const { error: authError } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (authError) throw authError; })} />{error && <Text style={styles.error}>{error}</Text>}</SafeAreaView>;
  if (page === 'stores') return <SafeAreaView style={styles.screen}><Header title="店舗を選択" onLogout={() => void supabase.auth.signOut()} />{loading ? <ActivityIndicator /> : <FlatList data={stores} keyExtractor={(item) => item.id} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => void selectStore(item)}><Text style={styles.rowTitle}>{item.name}</Text><Text>{item.role}</Text></TouchableOpacity>} ListEmptyComponent={<Centered message="利用可能な店舗がありません。" />} />}{error && <Text style={styles.error}>{error}</Text>}</SafeAreaView>;
  if (page === 'today') return <Screen title={store?.name || 'GARAGE LINK'} onStore={() => setPage('stores')} onLogout={() => void supabase.auth.signOut()} nav={nav} error={error}><TodayScreen today={today} onMaintenance={() => void openMaintenance()} tablet={tablet} /></Screen>;
  if (page === 'vehicleDetail' && vehicle && store) return <Screen title="車両詳細" onBack={() => void openVehicles()} nav={nav} error={error}><ScrollView contentContainerStyle={tablet ? styles.tabletDetail : undefined}><Text style={styles.heading}>{[vehicle.vehicle.maker, vehicle.vehicle.modelName].filter(Boolean).join(' ') || '車両'}</Text><Text>管理番号: {vehicle.vehicle.managementNo || '-'}</Text><Text>状態: {vehicle.vehicle.status || '-'}</Text><View style={styles.actions}><Button title="在庫中" onPress={() => void changeVehicleStatus('在庫中')} /><Button title="整備中" onPress={() => void changeVehicleStatus('整備中')} /></View><View style={styles.actions}><Button title="カメラで追加" onPress={() => void addPhoto(true)} /><Button title="写真から追加" onPress={() => void addPhoto(false)} /></View>{vehicle.imageFiles.map((item) => <SignedImage key={item.id} storeId={store.id} fileId={item.id} />)}{!vehicle.imageFiles.length && <Text style={styles.muted}>画像はまだありません。</Text>}</ScrollView></Screen>;
  if (page === 'vehicles') return <Screen title={store?.name || '車両'} onStore={() => setPage('stores')} nav={nav} error={error}><Search placeholder="車名・管理番号で検索" value={search} onChange={setSearch} onSearch={() => void openVehicles()} /><FlatList data={vehicles} keyExtractor={(item) => item.id} refreshing={loading} onRefresh={() => void openVehicles()} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => void openVehicle(item)}><Text style={styles.rowTitle}>{[item.maker, item.modelName].filter(Boolean).join(' ') || item.managementNo || '名称未設定'}</Text><Text>{item.status || '-'}</Text></TouchableOpacity>} ListEmptyComponent={<Centered message="車両がありません。" />} /></Screen>;
  if (page === 'maintenanceDetail' && job) return <Screen title="整備詳細" onBack={() => void openMaintenance()} nav={nav} error={error}><Text style={styles.heading}>{job.job_no || '整備案件'}</Text><Text>種別: {job.job_type || '-'}</Text><Text>状態: {job.status || '-'}</Text><Text>納車予定: {date(job.scheduled_delivery_at)}</Text><Text>担当: {job.assigned_user_name || '-'}</Text><View style={styles.actions}><Button title="受付" onPress={() => void updateJob('received')} /><Button title="作業中" onPress={() => void updateJob('working')} /><Button title="完了" onPress={() => void updateJob('completed')} /></View></Screen>;
  if (page === 'maintenance') return <Screen title="整備・車検" onStore={() => setPage('stores')} nav={nav} error={error}><FlatList data={jobs} keyExtractor={(item) => item.id} refreshing={loading} onRefresh={() => void openMaintenance()} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => void openJob(item)}><Text style={styles.rowTitle}>{item.job_no || '整備案件'} / {item.job_type || '-'}</Text><Text>{item.status || '-'}　納車予定: {date(item.scheduled_delivery_at)}</Text></TouchableOpacity>} ListEmptyComponent={<Centered message="整備案件がありません。" />} /></Screen>;
  if (page === 'customerDetail' && customer) return <Screen title="顧客詳細" onBack={() => void openCustomers()} nav={nav} error={error}><ScrollView contentContainerStyle={tablet ? styles.tabletDetail : undefined}><Text style={styles.heading}>{customer.customer.name || '顧客'}</Text><Text>{customer.customer.phone || customer.customer.mobile_phone || '-'}</Text><Text>{customer.customer.email || '-'}</Text><Text>{customer.customer.address || '-'}</Text><Text style={styles.section}>紐づく車両</Text>{customer.vehicles.map((item) => <Text key={item.id}>{[item.managementNo, item.maker, item.modelName].filter(Boolean).join(' / ')}</Text>)}<Text style={styles.section}>整備案件</Text>{customer.maintenance.map((item) => <Text key={item.id}>{item.job_no || '-'} / {item.status || '-'}</Text>)}<Button title="この顧客の見積を作成" onPress={startQuote} /></ScrollView></Screen>;
  if (page === 'customers') return <Screen title="顧客" onStore={() => setPage('stores')} nav={nav} error={error}><Search placeholder="顧客名・電話番号で検索" value={search} onChange={setSearch} onSearch={() => void openCustomers()} /><FlatList data={customers} keyExtractor={(item) => item.id} refreshing={loading} onRefresh={() => void openCustomers()} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => void openCustomer(item)}><Text style={styles.rowTitle}>{item.name || '名称未設定'}</Text><Text>{item.phone || item.mobile_phone || '-'}</Text></TouchableOpacity>} ListEmptyComponent={<Centered message="顧客がありません。" />} /></Screen>;
  if (page === 'quoteCreate') return <Screen title="見積を作成" onBack={() => setPage('customerDetail')} nav={nav} error={error}><ScrollView contentContainerStyle={styles.form}><Text>顧客: {customer?.customer.name || '-'}</Text><TextInput style={styles.input} placeholder="見積タイトル（任意）" value={quoteTitle} onChangeText={setQuoteTitle} /><TextInput style={styles.input} placeholder="販売明細名" value={itemName} onChangeText={setItemName} /><TextInput style={styles.input} placeholder="販売価格（税抜・円）" keyboardType="numeric" value={itemPrice} onChangeText={setItemPrice} /><Text style={styles.muted}>原価・利益・内部メモはアプリに表示・送信されません。</Text><Button title="保存して読戻す" onPress={() => void saveQuote()} /></ScrollView></Screen>;
  if (page === 'quotePreview' && quote) return <Screen title="お客様向けプレビュー" onBack={() => void openQuotes()} nav={nav} error={error}><ScrollView contentContainerStyle={tablet ? styles.tabletPreview : styles.preview}><Text style={styles.previewTitle}>御見積書</Text><Text>見積番号: {quote.quoteNo || '-'}</Text><Text>宛先: {quote.customerName || '-'} {quote.customerHonorific || '様'}</Text><Text>車両: {quote.vehicleLabel || '-'}</Text>{quote.items.map((item) => <View key={item.id || item.name} style={styles.quoteItem}><Text>{item.name}　{item.quantity} × {yen(item.unitPrice)}</Text><Text>{yen(item.amount)}</Text></View>)}<Text style={styles.total}>合計 {yen(quote.totalAmount)}</Text><View style={styles.actions}><Button title="PDF作成" onPress={() => void exportPdf(false)} /><Button title="共有" onPress={() => void exportPdf(true)} /><Button title="印刷" onPress={() => void printQuote()} /></View></ScrollView></Screen>;
  return <Screen title="見積" onStore={() => setPage('stores')} nav={nav} error={error}><FlatList data={quotes} keyExtractor={(item) => item.id} refreshing={loading} onRefresh={() => void openQuotes()} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => void openQuote(item)}><Text style={styles.rowTitle}>{item.quoteNo || '見積'} / {item.customerName || '-'}</Text><Text>{yen(item.totalAmount)}</Text></TouchableOpacity>} ListEmptyComponent={<Centered message="見積がありません。顧客画面から作成できます。" />} /></Screen>;
}

function Screen({ title, onBack, onStore, onLogout, nav, error, children }: { title: string; onBack?: () => void; onStore?: () => void; onLogout?: () => void; nav: React.ReactNode; error: string | null; children: React.ReactNode }) { return <SafeAreaView style={styles.screen}><Header title={title} onBack={onBack || onStore} backTitle={onBack ? '戻る' : '店舗'} onLogout={onLogout} />{nav}{children}{error && <Text style={styles.error}>{error}</Text>}</SafeAreaView>; }
function Header({ title, onBack, backTitle = '戻る', onLogout }: { title: string; onBack?: () => void; backTitle?: string; onLogout?: () => void }) { return <View style={styles.header}>{onBack ? <Button title={backTitle} onPress={onBack} /> : <View style={styles.headerSpacer} />}<Text style={styles.headerTitle}>{title}</Text>{onLogout ? <Button title="ログアウト" onPress={onLogout} /> : <View style={styles.headerSpacer} />}</View>; }
function Nav({ active, onToday, onVehicles, onMaintenance, onCustomers, onQuotes }: { active: Page; onToday: () => void; onVehicles: () => void; onMaintenance: () => void; onCustomers: () => void; onQuotes: () => void }) { return <View style={styles.nav}>{[['today', '今日', onToday], ['vehicles', '車両', onVehicles], ['maintenance', '整備', onMaintenance], ['customers', '顧客', onCustomers], ['quotes', '見積', onQuotes]].map(([key, label, action]) => <TouchableOpacity key={key as string} style={[styles.navButton, active === key && styles.navButtonActive]} onPress={action as () => void}><Text style={active === key ? styles.navTextActive : styles.navText}>{label as string}</Text></TouchableOpacity>)}</View>; }
function TodayScreen({ today, onMaintenance, tablet }: { today: Today | null; onMaintenance: () => void; tablet: boolean }) { if (!today) return <Centered message="今日の予定を読み込んでいます。" />; const groups: Array<[string, Today['appointments']]> = [['今日の予約', today.appointments], ['納車予定', today.deliveries], ['未完了', today.incompleteWork], ['担当作業', today.assignedWork]]; return <ScrollView contentContainerStyle={tablet ? styles.todayTablet : styles.today}>{groups.map(([title, items]) => <View key={title} style={styles.card}><Text style={styles.section}>{title}</Text>{items.length ? items.slice(0, 8).map((item) => <TouchableOpacity key={item.id} onPress={onMaintenance}><Text style={styles.rowTitle}>{item.job_no || item.appointment_type || item.job_type || '予定'}</Text><Text>{item.status || '-'}　{date(item.scheduled_at || item.scheduled_delivery_at || item.scheduled_in_at)}</Text></TouchableOpacity>) : <Text style={styles.muted}>該当なし</Text>}</View>)}</ScrollView>; }
function Search({ placeholder, value, onChange, onSearch }: { placeholder: string; value: string; onChange: (value: string) => void; onSearch: () => void }) { return <View style={styles.search}><TextInput style={styles.searchInput} placeholder={placeholder} value={value} onChangeText={onChange} onSubmitEditing={onSearch} /><Button title="検索" onPress={onSearch} /></View>; }
function Centered({ message }: { message: string }) { return <View style={styles.center}><Text style={styles.muted}>{message}</Text></View>; }
function SignedImage({ storeId, fileId }: { storeId: string; fileId: string }) { const [url, setUrl] = useState<string | null>(null); useEffect(() => { void mobileApi.signedUrl(storeId, fileId).then((result) => setUrl(result.signedUrl)).catch(() => setUrl(null)); }, [storeId, fileId]); return url ? <Image source={{ uri: url }} style={styles.image} /> : <ActivityIndicator />; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#f8fafc', padding: 18, gap: 12 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, brand: { color: '#0f3b62', fontSize: 28, fontWeight: '800', marginTop: 40 }, heading: { fontSize: 21, fontWeight: '700', color: '#102a43' }, input: { borderWidth: 1, borderColor: '#cbd5e1', backgroundColor: 'white', borderRadius: 8, padding: 13 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerSpacer: { width: 70 }, headerTitle: { color: '#102a43', fontSize: 18, fontWeight: '700' }, nav: { flexDirection: 'row', gap: 4, borderBottomWidth: 1, borderColor: '#cbd5e1', paddingBottom: 7 }, navButton: { flex: 1, paddingVertical: 7, alignItems: 'center', borderRadius: 6 }, navButtonActive: { backgroundColor: '#102a43' }, navText: { color: '#334155', fontSize: 12 }, navTextActive: { color: 'white', fontSize: 12, fontWeight: '700' }, row: { backgroundColor: 'white', borderRadius: 10, padding: 16, marginVertical: 5, borderWidth: 1, borderColor: '#e2e8f0' }, rowTitle: { fontSize: 16, fontWeight: '700', color: '#102a43', marginBottom: 5 }, search: { flexDirection: 'row', gap: 8 }, searchInput: { flex: 1, borderWidth: 1, borderColor: '#cbd5e1', backgroundColor: 'white', borderRadius: 8, padding: 10 }, actions: { flexDirection: 'row', justifyContent: 'space-around', gap: 6, marginVertical: 8 }, image: { height: 220, width: '100%', borderRadius: 8, marginVertical: 8 }, error: { color: '#b91c1c' }, muted: { color: '#64748b' }, section: { color: '#0f3b62', fontWeight: '700', fontSize: 16, marginTop: 8, marginBottom: 6 }, today: { gap: 10 }, todayTablet: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, card: { backgroundColor: 'white', borderRadius: 10, padding: 14, borderWidth: 1, borderColor: '#e2e8f0', minWidth: 260, flexGrow: 1, flexBasis: 280 }, tabletDetail: { maxWidth: 760, alignSelf: 'center', width: '100%', gap: 10 }, tabletPreview: { maxWidth: 720, alignSelf: 'center', width: '100%', backgroundColor: 'white', padding: 28, gap: 12 }, preview: { backgroundColor: 'white', padding: 20, gap: 12 }, previewTitle: { fontSize: 25, fontWeight: '800', color: '#102a43' }, quoteItem: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: '#e2e8f0', paddingVertical: 8 }, total: { fontWeight: '800', color: '#102a43', fontSize: 20, textAlign: 'right' }, form: { gap: 12 } });
