const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const origin={};vm.runInNewContext(compile('src/apiOrigin.ts'),{exports:origin,URL,__DEV__:false});
let response;const contract={};vm.runInNewContext(compile('src/captchaContract.ts'),{exports:contract,URL,process:{env:{EXPO_PUBLIC_APP_BASE_URL:'https://app.example.invalid'}},require:n=>n==='./apiOrigin'?origin:n==='./authTransport'?{authFetch:async()=>response}:(()=>{throw Error('unexpected dependency')})()});
(async()=>{const url=contract.captchaUrl();assert.equal(url,'https://app.example.invalid/api/auth/mobile-captcha');
for(const message of ['not-json',JSON.stringify({type:'session',access_token:'synthetic'}),JSON.stringify({type:'captcha-token',token:''}),JSON.stringify({type:'captcha-token',token:'a'.repeat(2049)}),JSON.stringify({type:'captcha-token',token:'with space'}),'a'.repeat(4097)])assert.equal(contract.readCaptchaMessage(url,url,message),null);
const token=JSON.stringify({type:'captcha-token',token:'synthetic-captcha'});assert.equal(contract.readCaptchaMessage('https://evil.invalid',url,token),null);assert.equal(contract.readCaptchaMessage(url+'?redirect=1',url,token),null);assert.equal(contract.readCaptchaMessage(url,url,token).token,'synthetic-captcha');for(const type of ['captcha-error','captcha-expired'])assert.equal(contract.readCaptchaMessage(url,url,JSON.stringify({type})).ready,false);
assert.equal(contract.allowedCaptchaNavigation(url,url,true),true);assert.equal(contract.allowedCaptchaNavigation('https://challenges.cloudflare.com/turnstile',url,false),true);assert.equal(contract.allowedCaptchaNavigation('https://challenges.cloudflare.com/turnstile',url,true),false);for(const bad of ['file:///tmp/a','javascript:alert(1)','https://evil.invalid','https://challenges.cloudflare.com.evil.invalid'])assert.equal(contract.allowedCaptchaNavigation(bad,url,false),false);
response=Response.json({enabled:false,siteKey:null});assert.equal((await contract.loadCaptchaConfig()).enabled,false);response=Response.json({enabled:true,siteKey:'synthetic-key'});assert.equal((await contract.loadCaptchaConfig()).enabled,true);for(const body of [{enabled:true,siteKey:null},{enabled:'false'},{}]){response=Response.json(body);await assert.rejects(contract.loadCaptchaConfig());}response=Response.json({enabled:false},{status:503});await assert.rejects(contract.loadCaptchaConfig());console.log('MOBILE_CAPTCHA_CONTRACT=PASS');})().catch(e=>{console.error(e.name);process.exitCode=1});
